---
  - name: chk tomcat running
    shell: ps axf | grep "{{tomcat_install_dir}}/bin" | grep -v grep
    ignore_errors: true
    register: tomcat_run_check

  - name: stop tomcat
    command: "{{tomcat_install_dir}}/bin/shutdown.sh"
    ignore_errors: true
    when: tomcat_run_check.rc != "" and tomcat_run_check.rc == 0

  - name: Wait for tomcat stop
    wait_for: port=8080 state=stopped host={{inventory_hostname}}
